In [1]:
import user_functions, pandas
from sklearn import ensemble
import numpy as np

In [2]:
guided_motion_filenames = ["ExampleData/FourSpeedData/accR.csv", "ExampleData/FourSpeedData/gyrR.csv", 
                           "ExampleData/FourSpeedData/accL.csv", "ExampleData/FourSpeedData/gyrL.csv"]
guided_keylog_filename = "ExampleData/FourSpeedData/log.csv"

[[normalized_data],  # List of normalized data sets, with each motions axes in a separate DataFrame
 [combined_axes_data],    # List of normalized data sets, with all motion axes for each set in one DataFrame
 [peaks_indices],       # Indices of peaks for each column of combined
 [keylog_data],
 mouselogs] = user_functions.package_data([guided_motion_filenames], [guided_keylog_filename], [])

In [3]:
user_functions.sync_time(keylog_data, combined_axes_data.index[504])


In [4]:
keylog_data['UNX2'] = keylog_data.Time.astype('int64')//10**6
keylog_data

Time     Char           UNX2
1   2017-07-17 19:12:42.575  <Enter>  1500318762575
2   2017-07-17 19:12:47.876  <Enter>  1500318767876
3   2017-07-17 19:12:58.960        e  1500318778960
4   2017-07-17 19:12:59.483        z  1500318779483
5   2017-07-17 19:13:00.016        ܂  1500318780016
6   2017-07-17 19:13:00.526        n  1500318780526
7   2017-07-17 19:13:01.074        p  1500318781074
8   2017-07-17 19:13:01.584        k  1500318781584
9   2017-07-17 19:13:02.165        e  1500318782165
10  2017-07-17 19:13:02.724        a  1500318782724
11  2017-07-17 19:13:03.362  <Enter>  1500318783362
12  2017-07-17 19:13:06.519        e  1500318786519
13  2017-07-17 19:13:07.123        k  1500318787123
14  2017-07-17 19:13:07.640        e  1500318787640
15  2017-07-17 19:13:08.249        x  1500318788249
16  2017-07-17 19:13:08.887        t  1500318788887
17  2017-07-17 19:13:09.503        r  1500318789503
18  2017-07-17 19:13:10.112        i  1500318790112
19  2017-07-17 19:13:10.807        x  1500318790807
20  2017-07-17 19:13:11.392  <Enter>  1500318791392
21  2017-07-17 19:13:15.222        t  1500318795222
22  2017-07-17 19:13:15.781        e  1500318795781
23  2017-07-17 19:13:16.329        n  1500318796329
24  2017-07-17 19:13:16.855        p  1500318796855
25  2017-07-17 19:13:17.465        e  1500318797465
26  2017-07-17 19:13:17.936        r  1500318797936
27  2017-07-17 19:13:18.401        ܂  1500318798401
28  2017-07-17 19:13:18.952        t  1500318798952
29  2017-07-17 19:13:19.628        u  1500318799628
30  2017-07-17 19:13:20.197        r  1500318800197
..                      ...      ...            ...
592 2017-07-17 19:17:27.781        e  1500319047781
593 2017-07-17 19:17:27.930        a  1500319047930
594 2017-07-17 19:17:28.059  <Enter>  1500319048059
595 2017-07-17 19:17:29.538        q  1500319049538
596 2017-07-17 19:17:29.642        u  1500319049642
597 2017-07-17 19:17:29.882        o  1500319049882
598 2017-07-17 19:17:30.044        t  1500319050044
599 2017-07-17 19:17:30.235        ܂  1500319050235
600 2017-07-17 19:17:30.346        t  1500319050346
601 2017-07-17 19:17:30.475        i  1500319050475
602 2017-07-17 19:17:30.567        o  1500319050567
603 2017-07-17 19:17:30.631        b  1500319050631
604 2017-07-17 19:17:30.772        a  1500319050772
605 2017-07-17 19:17:30.877  <Enter>  1500319050877
606 2017-07-17 19:17:37.855        a  1500319057855
607 2017-07-17 19:17:37.976        u  1500319057976
608 2017-07-17 19:17:38.113        s  1500319058113
609 2017-07-17 19:17:38.233        o  1500319058233
610 2017-07-17 19:17:38.380           1500319058380
611 2017-07-17 19:17:38.554        k  1500319058554
612 2017-07-17 19:17:38.745        o  1500319058745
613 2017-07-17 19:17:38.862        f  1500319058862
614 2017-07-17 19:17:38.969        j  1500319058969
615 2017-07-17 19:17:39.077        e  1500319059077
616 2017-07-17 19:17:39.234        y  1500319059234
617 2017-07-17 19:17:39.394        a  1500319059394
618 2017-07-17 19:17:39.525           1500319059525
619 2017-07-17 19:17:39.804        -  1500319059804
620 2017-07-17 19:17:40.101        j  1500319060101
621 2017-07-17 19:17:40.309  <Enter>  1500319060309

[621 rows x 3 columns]

In [5]:
combined_axes_data['UNX2'] = combined_axes_data.index.astype('int64')//10**6
combined_axes_data

AccXR     AccYR     AccZR     GyrXR     GyrYR  \
Time                                                                        
2017-07-17 19:12:31.632 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.658 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.685 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.711 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.738 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.764 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.791 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.817 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.844 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.870 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.897 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.923 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.950 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:31.976 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.003 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.029 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.056 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.082 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.109 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.135 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.178 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.217 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.257 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.296 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.336 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.375 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.415 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.454 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.494 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
2017-07-17 19:12:32.533 -0.065918 -0.033813 -0.016846  0.000229  0.004501   
...                           ...       ...       ...       ...       ...   
2017-07-17 19:17:40.284  0.131616  0.033850 -0.093176 -0.108155 -0.145675   
2017-07-17 19:17:40.302  0.199219  0.038574 -0.137817  0.015144 -0.446014   
2017-07-17 19:17:40.320  0.197131  0.015137 -0.091785  0.064514 -0.174996   
2017-07-17 19:17:40.332  0.195740 -0.000488 -0.061096  0.097427  0.005684   
2017-07-17 19:17:40.356  0.192957 -0.031738  0.000281  0.065750 -0.002678   
2017-07-17 19:17:40.362  0.192261 -0.039551  0.015625  0.057831 -0.004768   
2017-07-17 19:17:40.391  0.118749 -0.014881  0.037363  0.016551 -0.060398   
2017-07-17 19:17:40.397  0.103540 -0.009777  0.041861  0.008011 -0.071907   
2017-07-17 19:17:40.420  0.045238  0.009789  0.059101  0.001960  0.001854   
2017-07-17 19:17:40.426  0.030029  0.014893  0.063599  0.000381  0.021095   
2017-07-17 19:17:40.450  0.032065  0.011715  0.019604  0.005630  0.084724   
2017-07-17 19:17:40.456  0.032574  0.010920  0.008605  0.006943  0.100632   
2017-07-17 19:17:40.479  0.034525  0.007875 -0.033557 -0.038046  0.010654   
2017-07-17 19:17:40.485  0.035034  0.007080 -0.044556 -0.049782 -0.012817   
2017-07-17 19:17:40.509  0.033942 -0.001759 -0.036511 -0.038460  0.002258   
2017-07-17 19:17:40.515  0.033669 -0.003968 -0.034500 -0.035629  0.006027   
2017-07-17 19:17:40.538  0.032622 -0.012439 -0.026791 -0.049970  0.001398   
2017-07-17 19:17:40.544  0.032349 -0.014648 -0.024780 -0.053711  0.000191   
2017-07-17 19:17:40.568  0.042826 -0.011719 -0.015495 -0.022644  0.020759   
2017-07-17 19:17:40.574 

In [6]:
keylog_np = pandas.DataFrame.as_matrix(keylog_data)
combined_axes_np = pandas.DataFrame.as_matrix(combined_axes_data)

In [7]:
starttime = keylog_np[0][2]
keylog_np[:,2] = keylog_np[:,2] - starttime
combined_axes_np[:,12] = combined_axes_np[:,12] - starttime
combined_axes_np = combined_axes_np[504:,:]

In [8]:
from scipy.interpolate import interp1d
time_x = combined_axes_np[:,12]
data_y = combined_axes_np[:,:12]
f2 = interp1d(np.transpose(time_x), np.transpose(data_y), kind='cubic')
time_new = np.linspace(0, 298140, 29815)
print(time_new)
print(np.shape(time_x))

[  0.00000000e+00   1.00000000e+01   2.00000000e+01 ...,   2.98120000e+05
   2.98130000e+05   2.98140000e+05]
(18039,)


In [9]:
interpolated = np.transpose(f2(time_new))
interpolated = interpolated[0:29780,:]
print(interpolated)
print(np.shape(interpolated))

[[  2.65136719e-01   3.36914062e-02   1.51611328e-01 ...,   7.97161646e-04
   -6.26771096e-02  -2.31531357e-04]
 [  2.27836895e-01   2.71912796e-02   1.07711038e-01 ...,   2.75367400e-03
   -7.73268988e-02  -3.86611118e-03]
 [  1.90533498e-01   2.06897263e-02   6.38113489e-02 ...,   5.13839716e-03
   -6.96236964e-02  -1.00585547e-02]
 ..., 
 [  1.93962138e-01  -1.65832110e-02  -2.89903622e-02 ...,  -1.80783972e-02
   -7.24423364e-03  -1.22489416e-02]
 [  1.92914454e-01  -3.02669800e-02  -2.44030878e-03 ...,  -2.04419982e-02
   -1.36201973e-02  -1.39099677e-02]
 [  1.89415574e-01  -4.12079309e-02   2.13826843e-02 ...,  -2.27585163e-02
   -6.89642294e-03  -1.53773758e-02]]
(29780, 12)


In [10]:
leng = len(interpolated)
leng

29780

In [11]:
data_slide = np.zeros((29770,10,12))
for i in range(0,leng-10): #100ms
    data_slide[i,:,:] = interpolated[i:i+10,:]
    
print (data_slide.shape)

(29770, 10, 12)


In [12]:
data_pause = np.zeros((29680,100,12))
for i in range(0,leng-100): #1000ms
    data_pause[i,:,:] = interpolated[i:i+100,:]

print(data_pause.shape)

(29680, 100, 12)


In [13]:
myset = set(keylog_np[:,1])
keylog_np_2 = np.copy(keylog_np)
myset

{' ',
 '-',
 '<BckSp>',
 '<Enter>',
 '\\',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'x',
 'y',
 'z',
 '܂'}

[[Timestamp('2017-07-17 19:12:42.575000') '<Enter>' 0]
 [Timestamp('2017-07-17 19:12:47.876000') '<Enter>' 5301]
 [Timestamp('2017-07-17 19:12:58.960000') 'e' 16385]
 ..., 
 [Timestamp('2017-07-17 19:17:39.804000') '-' 297229]
 [Timestamp('2017-07-17 19:17:40.101000') 'j' 297526]
 [Timestamp('2017-07-17 19:17:40.309000') '<Enter>' 297734]]


In [44]:
labels = np.zeros((29780,1))
for key in keylog_np:
    index = int(key[2]/10)
    if key[1]== '<Enter>':
        labels[index] = 2
    elif key[1]== ' ':
        labels[index] = 2
    else:
        labels[index] = 1
    
print(np.sum(labels))
print (labels)
print(labels.shape)

684.0
[[ 2.]
 [ 0.]
 [ 0.]
 ..., 
 [ 0.]
 [ 0.]
 [ 0.]]
(29780, 1)


In [46]:
labels_sliding = np.zeros((29770,1))
for i in range(0,leng-10): #100ms
    labels_sliding[i] = np.amax(labels[i:i+10])

print(np.sum(labels_sliding))
print (np.reshape(labels_sliding,(10,2977)))
print(labels_sliding.shape)

6773.0
[[ 2.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  1.  1.  1.]
 [ 1.  1.  1. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  2.  2.  2.]]
(29770, 1)


In [23]:
labels_sliding = np.zeros((29770,1))
for i in range(0,leng-10): #100ms
    if labels[i]==1:
        labels_sliding[i:i+10] = 1

print(np.sum(labels_sliding))
print (np.reshape(labels_sliding,(10,2977)))
print(labels_sliding.shape)

620.0
[[ 1.  1.  1. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  0.  0.  0.]
 [ 0.  0.  0. ...,  1.  1.  1.]
 [ 1.  1.  0. ...,  0.  0.  0.]]
(29770, 1)


In [24]:
keylog_np_2[604]
#array([Timestamp('2017-07-17 19:17:37.855000'), 'a', 295280], dtype=object)

array([Timestamp('2017-07-17 19:17:30.877000'), '<Enter>', 288302], dtype=object)

In [47]:
print(labels_sliding[28832])

[ 0.]


In [48]:
import numpy as np
import scipy.io

import keras
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, LSTM, Dense, Dropout, Flatten
from keras.layers.core import Permute, Reshape
from keras import backend as K
from hmmlearn import hmm

np.random.seed(2)

In [49]:
X_train0 = data_slide[:26000]
Y_train = labels_sliding[0:26000].reshape(-1).astype(np.uint8)
X_test0 = data_slide[26000:]
Y_test = labels_sliding[26000:]
print(np.shape(X_train0))
print(np.shape(Y_train))
print(np.shape(X_test0))
print(np.shape(Y_test))

(26000, 10, 12)
(26000,)
(3770, 10, 12)
(3770, 1)


In [50]:
num_classes = 3
Y_train = keras.utils.to_categorical(Y_train, num_classes)
Y_test = keras.utils.to_categorical(Y_test, num_classes)

In [51]:
def _data_reshaping(X_tr, X_va, network_type):
    _, win_len, dim = X_tr.shape
    print(network_type)
    if network_type=='CNN' or network_type=='ConvLSTM':
        
        # make it into (frame_number, dimension, window_size, channel=1) for convNet
        X_tr = np.swapaxes(X_tr,1,2)
        X_va = np.swapaxes(X_va,1,2)

        X_tr = np.reshape(X_tr, (-1, dim, win_len, 1))
        X_va = np.reshape(X_va, (-1, dim, win_len, 1))
        
    if network_type=='MLP':
        print('MLP...')
        X_tr = np.reshape(X_tr, (-1, dim*win_len))
        X_va = np.reshape(X_va, (-1, dim*win_len))
    
    return X_tr, X_va


In [52]:

def model_variant(model, num_feat_map, dim, network_type):
    print(network_type)
    if network_type == 'ConvLSTM':
        model.add(Permute((2, 1, 3))) # for swap-dimension
        model.add(Reshape((-1,num_feat_map*dim)))
        model.add(LSTM(32, return_sequences=False, stateful=False))
        model.add(Dropout(0.5))
    if network_type == 'CNN':
        
        model.add(Flatten())
        model.add(Dense(32, activation='relu'))
        model.add(Dropout(0.5))

        
def model_conv(model, num_feat_map):
    model.add(Conv2D(num_feat_map, kernel_size=(1, 5),
                 activation='relu',
                 input_shape=(dim, win_len, 1),
                 padding='same'))
    model.add(MaxPooling2D(pool_size=(1, 2)))
    model.add(Dropout(0.5))
    model.add(Conv2D(num_feat_map, kernel_size=(1, 5), activation='relu',padding='same'))
    model.add(MaxPooling2D(pool_size=(1, 2)))
    model.add(Dropout(0.5))
    
def model_LSTM(model):
    model.add(LSTM(num_hidden_lstm, 
               input_shape=(win_len,dim), 
               return_sequences=True))
    model.add(Dropout(0.5))
    model.add(LSTM(num_hidden_lstm, return_sequences=False))
    model.add(Dropout(0.5))

def model_MLP(model, num_hidden_mlp):
    model.add(Dense(num_hidden_mlp, activation='relu', input_shape=(dim*win_len,)))
    model.add(Dropout(0.5))
    model.add(Dense(num_hidden_mlp, activation='relu'))
    model.add(Dropout(0.5))
    
def model_output(model):
    model.add(Dense(num_classes, activation='softmax'))
    

In [53]:
batch_size = 512
num_feat_map = 16
num_hidden_mlp = 128
num_hidden_lstm = 64

#network_type = 'CNN'
network_type = 'ConvLSTM'
#network_type = 'LSTM'
#network_type = 'MLP'
_, win_len, dim = X_train0.shape
print(win_len)
print(dim)

X_train, X_test = _data_reshaping(X_train0, X_test0, network_type)


10
12
ConvLSTM


In [40]:
print(X_train.shape)

(26000, 12, 10, 1)


In [54]:

print('building the model ... ')
model = Sequential()


if network_type=='CNN' or network_type=='ConvLSTM':
    model_conv(model, num_feat_map)
    model_variant(model, num_feat_map, dim, network_type)
if network_type=='LSTM':
    model_LSTM(model)
if network_type=='MLP': 
    model_MLP(model, num_hidden_mlp) 
    
    
    
    
model_output(model)    
model.summary()


building the model ... 
ConvLSTM
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 12, 10, 16)        96        
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 12, 5, 16)         0         
_________________________________________________________________
dropout_7 (Dropout)          (None, 12, 5, 16)         0         
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 12, 5, 16)         1296      
_________________________________________________________________
max_pooling2d_6 (MaxPooling2 (None, 12, 2, 16)         0         
_________________________________________________________________
dropout_8 (Dropout)          (None, 12, 2, 16)         0         
_________________________________________________________________
permute_3 (Permute)          (None, 2, 12, 

In [55]:
epochs = 10

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer='adam',
              metrics=['accuracy'])

H = model.fit(X_train, Y_train,
            batch_size=batch_size,
            epochs=epochs,
            verbose=1,
            shuffle=True,
            validation_data=(X_test, Y_test))


Train on 26000 samples, validate on 3770 samples
Epoch 1/10
26000/26000 [==============================] - 5s - loss: 0.7898 - acc: 0.7775 - val_loss: 0.7579 - val_acc: 0.6907
Epoch 2/10
26000/26000 [==============================] - 4s - loss: 0.5772 - acc: 0.8077 - val_loss: 0.7513 - val_acc: 0.6907
Epoch 3/10
26000/26000 [==============================] - 4s - loss: 0.5605 - acc: 0.8081 - val_loss: 0.7016 - val_acc: 0.6907
Epoch 4/10
26000/26000 [==============================] - 4s - loss: 0.5287 - acc: 0.8072 - val_loss: 0.5650 - val_acc: 0.7072
Epoch 5/10
26000/26000 [==============================] - 4s - loss: 0.4825 - acc: 0.8098 - val_loss: 0.5116 - val_acc: 0.7446
Epoch 6/10
26000/26000 [==============================] - 4s - loss: 0.4625 - acc: 0.8132 - val_loss: 0.4944 - val_acc: 0.7907
Epoch 7/10
26000/26000 [==============================] - 4s - loss: 0.4503 - acc: 0.8155 - val_loss: 0.4783 - val_acc: 0.7963
Epoch 8/10
26000/26000 [==============================] - 4s -

In [56]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

y_pred = np.argmax(model.predict(X_test), axis=1)
y_true = np.argmax(Y_test, axis=1)
cf_matrix = confusion_matrix(y_true, y_pred)
print(cf_matrix)
class_wise_f1 = np.round(f1_score(y_true, y_pred, average=None)*100)*0.01
print('the mean-f1 score: {:.2f}'.format(np.mean(class_wise_f1)))


[[2363  218   23]
 [ 423  617    0]
 [  67   14   45]]
the mean-f1 score: 0.66


In [ ]:
## MLP
[[ 710  303]
 [  57 2610]]
the mean-f1 score: 0.87

## LSTM
[[ 742  271]
 [ 138 2529]]
    
## CNN
[[ 784  229]
 [  76 2591]]

## ConvLSTM
[[ 905  108]
 [ 128 2539]]
the mean-f1 score: 0.92

In [ ]:
import matplotlib.pyplot as plt